#!/bin/sh

pwd | lolcat
wd=`pwd`

# build
$wd/gradlew build

# run test
$wd/gradlew test

# run db in background
~/src/h2/bin/h2.sh &
java -jar $wd/build/libs/*-SNAPSHOT.jar | lolcat

# kill all java processes
pkill java
